# Numpy basics

In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3,5)

In [3]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
print(a.ndim)

2


In [5]:
print(a.shape)

(3, 5)


In [6]:
print(a.size)

15


In [7]:
print(a.dtype)

int64


In [8]:
print(type(a))

<class 'numpy.ndarray'>


In [9]:
b = np.array([1.0, 2.0, 3.0, 4.0])
print(b)
print(b.dtype)

[1. 2. 3. 4.]
float64


In [10]:
array = [1,2,3,4,5,6]
np_array = np.array(array)
print(np_array)

[1 2 3 4 5 6]


In [11]:
c = np.zeros((10,10), dtype = np.int64)
print(c)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [12]:
#linspace
temp = np.linspace(0,1,11, endpoint=True)
print(temp)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [13]:
temp = np.linspace(0,20, 50, endpoint=False)
print(temp)

[ 0.   0.4  0.8  1.2  1.6  2.   2.4  2.8  3.2  3.6  4.   4.4  4.8  5.2
  5.6  6.   6.4  6.8  7.2  7.6  8.   8.4  8.8  9.2  9.6 10.  10.4 10.8
 11.2 11.6 12.  12.4 12.8 13.2 13.6 14.  14.4 14.8 15.2 15.6 16.  16.4
 16.8 17.2 17.6 18.  18.4 18.8 19.2 19.6]


In [14]:
#logspace
temp = np.logspace(-1, 2, 15, endpoint=False, base=10)
print(temp)

[ 0.1         0.15848932  0.25118864  0.39810717  0.63095734  1.
  1.58489319  2.51188643  3.98107171  6.30957344 10.         15.84893192
 25.11886432 39.81071706 63.09573445]


In [15]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly c

In [16]:
temp = np.fromfunction(lambda i, j: i + j, (3,3), dtype=int)
print(temp)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [17]:
def equation(x,y):
    return 15*x+y
temp = np.fromfunction(equation,(5,4), dtype=int)
print(temp)

[[ 0  1  2  3]
 [15 16 17 18]
 [30 31 32 33]
 [45 46 47 48]
 [60 61 62 63]]


# Operations

In [18]:
temp = np.arange(12).reshape(3,4)
print(temp)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [19]:
print(temp.sum(axis=0))

[12 15 18 21]


In [20]:
print(temp.sum(axis=1))

[ 6 22 38]


In [21]:
print(temp.min(),temp.max())

0 11


In [22]:
temp1 = a*np.pi/12
print(temp1)

[[0.         0.26179939 0.52359878 0.78539816 1.04719755]
 [1.30899694 1.57079633 1.83259571 2.0943951  2.35619449]
 [2.61799388 2.87979327 3.14159265 3.40339204 3.66519143]]


In [23]:
temp2 = np.cos(temp1)
print(temp2)

[[ 1.00000000e+00  9.65925826e-01  8.66025404e-01  7.07106781e-01
   5.00000000e-01]
 [ 2.58819045e-01  6.12323400e-17 -2.58819045e-01 -5.00000000e-01
  -7.07106781e-01]
 [-8.66025404e-01 -9.65925826e-01 -1.00000000e+00 -9.65925826e-01
  -8.66025404e-01]]


In [24]:
temp3 = temp1 + temp2
print(temp3)

[[1.         1.22772521 1.38962418 1.49250494 1.54719755]
 [1.56781598 1.57079633 1.57377667 1.5943951  1.64908771]
 [1.75196847 1.91386744 2.14159265 2.43746622 2.79916603]]


# Slicing

In [25]:
temp = np.fromfunction(equation, (5,4), dtype=int)
print(temp)

[[ 0  1  2  3]
 [15 16 17 18]
 [30 31 32 33]
 [45 46 47 48]
 [60 61 62 63]]


In [26]:
print(temp[1,1])

16


In [27]:
print(temp[0:2,0:2])

[[ 0  1]
 [15 16]]


In [28]:
print(temp[:,1])

[ 1 16 31 46 61]


In [29]:
print(temp.flatten())

[ 0  1  2  3 15 16 17 18 30 31 32 33 45 46 47 48 60 61 62 63]


In [30]:
for row in temp:
    print(row)

[0 1 2 3]
[15 16 17 18]
[30 31 32 33]
[45 46 47 48]
[60 61 62 63]


In [31]:
for temp in temp.flat:
    print(temp)

0
1
2
3
15
16
17
18
30
31
32
33
45
46
47
48
60
61
62
63


In [32]:
temp = np.arange(10)
print(temp)

[0 1 2 3 4 5 6 7 8 9]


In [33]:
temp.shape = (5,2)
print(temp)
print(temp.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(5, 2)


In [34]:
temp2 = np.arange(12)
temp3 = temp2[:]
print(temp3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [35]:
temp2.shape = (3,4)
print(temp2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [36]:
temp4 = temp3[:]
print(temp4)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [37]:
print(temp3.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [38]:
temp3[1] = -4

In [39]:
print(temp4)

[ 0 -4  2  3  4  5  6  7  8  9 10 11]


In [40]:
temp5 = temp3[3:8]
print(temp5)

[3 4 5 6 7]


In [41]:
temp5[:] = 0
print(temp5)

[0 0 0 0 0]


In [42]:
print(temp2 is temp3)
print(temp3.base is temp3)

False
False


In [43]:
print(temp4)

[ 0 -4  2  0  0  0  0  0  8  9 10 11]


In [44]:
temp3 = temp2.copy()

In [45]:
print(temp3)

[[ 0 -4  2  0]
 [ 0  0  0  0]
 [ 8  9 10 11]]


In [46]:
temp3[:,:] = 1
print(temp3)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [47]:
temp = np.arange(25).reshape(5,5)
print(temp)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [48]:
temp[temp > 10] = 0
print(temp)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]


In [49]:
temp[temp == 0] = 1
print(temp)

[[ 1  1  2  3  4]
 [ 5  6  7  8  9]
 [10  1  1  1  1]
 [ 1  1  1  1  1]
 [ 1  1  1  1  1]]


In [50]:
temp = np.arange(12).reshape(3,4)
temp[np.logical_and(temp > 2, temp<= 5)] = 0.0

In [51]:
print(temp)

[[ 0  1  2  0]
 [ 0  0  6  7]
 [ 8  9 10 11]]


In [52]:
print(temp > 5)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


In [53]:
np_temp = np.array(temp)
print(np_temp)

[[ 0  1  2  0]
 [ 0  0  6  7]
 [ 8  9 10 11]]


In [54]:
print(temp is np_temp)

False


In [55]:
print(np_temp.size)

12


In [56]:
print(temp.size)

12


In [57]:
print(np_temp > 5)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


In [58]:
print(np_array.dtype)

int64
